gomp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('obra/', include('obra.urls', namespace='obra')),
    path('contratista/', include('contratista.urls', namespace='contratista')),
    path('parametrizacion_multa/', include('parametrizacion_multa.urls', namespace='parametrizacion')),
     path('usuario/', include('usuario.urls', namespace='usuario')),
]

obra/urls.py
from django.urls import path
from .views import  ObraList, ObraCreate, ObraExpiredList, ObraUpdate, ObraDelete, ObraFinish, ObraFinishedList
from .reportes.obras import ReporteObra

app_name = 'obra'

urlpatterns = [
    path('list/', ObraList.as_view(), name='list'),
    path('expired/', ObraExpiredList.as_view(), name='list-exprired'),
    path('finished/', ObraFinishedList.as_view(), name='list-finished'),
    path('create/', ObraCreate.as_view(), name='create'),
    path('update/<int:pk>/', ObraUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ObraDelete.as_view(), name='delete'),
    path('report/<int:pk>/', ReporteObra.as_view(), name='report'),
    path('finish/<int:pk>/', ObraFinish.as_view(), name='finish'),
]

templates/parametrizacion/create.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <form action="{% url 'parametrizacion:create' %}" method="POST">
    </br> </br> 
        <h3 class="text-center">Agregar parametrizacion<a href="{% url 'parametrizacion:list' %}">lista</a></h3>
        
    </br> </br>    
        {% csrf_token %}
        {% for field in form.visible_fields %}
        {% endfor %}
        <div class="form-row">
            
            <div class="form-group col-md-6">
                <label for="textFirstName">Nombre Parametrización</label>
                {{ form.nombre}}

            </div>

            <div class="form-group col-md-6">
                    <label for="textFirstName">Valor Multa </label>
                    {{ form.porcentaje_valor_multa}}
        
            </div>

            <div class="form-group col-md-6">
                    <label for="textFirstName">Porcentaje inicial de desfase </label>
                    {{ form.porcentaje_desfase}}
        
            </div>

            <div class="form-group col-md-6">
                    <label for="textFirstName">Porcentaje incremental de desfase </label>
                    {{ form.porcentaje_desfase_incremental}}
        
            </div>

            

        
        <div class="col-xs-6 col-md-12">
            <div class="trans text-center">
            <button class="btn btn-info btn-responsive btninter" id="IdAgregar" class="btn btn-info" type="submit">Agregar</button>
            
            <button class="btn btn-danger btn-responsive btninter right" href="{% url 'parametrizacion:list' %}" id="IdCancelar" class="btn btn-danger"
                type="submit">Cancelar</button>

            </div>
        </div> 
    </form>
</div>
{% endblock content %}

templates/parametrizacion/delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="container">
<form action=" {% url 'parametrizacion:delete' object.id %}" method="POST">
</br>
<div class="trans text-center">
    <h3 class="text-center?">¿Desea eliminar la parametrización?</h3>
</div>
</br>
<div class="col-xs-6 col-md-12">
        <div class="trans text-center">
{% csrf_token %}
{{object.nombre }}
    </div>
</div>

</br>
</br>

<div class="col-xs-6 col-md-12">
    <div class="trans text-center">
        <div class="container"></div>

        <button id="IdAgregar" class="btn btn-info btn-responsive btninter" type="submit">Eliminar</button>
        <a href="{% url 'contratista:list' %}" id="IdAgregar" class="btn btn-danger btn-responsive btninter">Cancelar</a>

        </div>
    </div>
</div>

</form>
</div>
{% endblock content %}

templates/parametrizacion/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <h1 style="text-align: center">Parametrización Multa<a class="fas fa-fw fa-plus-circle" href="{% url 'parametrizacion:create' %}"></a></h1><br><br>
    <div id="accordion" class="accordion central_container_accordion">
        {% for parametrizacion in object_list %}
        <div class="card">
            <div class="card-header" id="heading-{{ parametrizacion.id }}">
                <h5 class="mb-0" data-toggle="collapse" data-target="#collapse-{{ parametrizacion.id }}" aria-expanded="true"
                    aria-controls="collapse-{{ parametrizacion.id }}">
                    {{ parametrizacion.nombre }}
                </h5>
            </div>

            <div id="collapse-{{ parametrizacion.id }}" class="collapse {% if forloop.first %}show{% endif %}"
                aria-labelledby="heading-{{ parametrizacion.id }}" data-parent="#accordion">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Nombre Parametrización: {{ parametrizacion.nombre }}</li>
                    <li class="list-group-item">Valor: {{ parametrizacion.porcentaje_valor_multa }}</li>
                    <li class="list-group-item">Porcentaje de desface inicial: {{ parametrizacion.porcentaje_desfase }}</li>
                    <li class="list-group-item">Porcentaje de desface incremental: {{ parametrizacion.porcentaje_desfase_incremental }}</li>
                </ul>
                <div class="text-center">
                <div class="card-body">
                    <a href="{% url 'parametrizacion:update' parametrizacion.id %}" class="btn btn-info">Modificar</a>
                    <a href="{% url 'parametrizacion:delete' parametrizacion.id%}" class="btn btn-danger">Eliminar</a>
                </div>
                </div>
            </div>
        </div>
        {% empty %}
        
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/parametrizacion/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
<form action=" {% url 'parametrizacion:update' object.id %}" method="POST">
    </br> </br> 
    <h3 class="text-center">Actualizar información</h3>
{% csrf_token %}
{% for field in form.visible_fields %}
{{ field.label_tag }}
{{ field }}
{% endfor %}
</br></br>
<div class="col-xs-6 col-md-12">
        <div class="trans text-center">
        <button class="btn btn-info btn-responsive btninter" id="IdAgregar" class="btn btn-info" type="submit">Agregar</button>
        
        <button class="btn btn-danger btn-responsive btninter right" href="{% url 'parametrizacion:list' %}" id="IdCancelar" class="btn btn-danger"
            type="submit">Cancelar</button>

        </div>
    </div> 

</form>
</div>
{% endblock content %}