gomp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('obra/', include('obra.urls', namespace='obra')),
    path('contratista/', include('contratista.urls', namespace='contratista')),
    path('parametrizacion_multa/', include('parametrizacion_multa.urls', namespace='parametrizacion')),
     path('usuario/', include('usuario.urls', namespace='usuario')),
]

obra/urls.py
from django.urls import path
from .views import  ObraList, ObraCreate, ObraExpiredList, ObraUpdate, ObraDelete, ObraFinish, ObraFinishedList
from .reportes.obras import ReporteObra

app_name = 'obra'

urlpatterns = [
    path('list/', ObraList.as_view(), name='list'),
    path('expired/', ObraExpiredList.as_view(), name='list-exprired'),
    path('finished/', ObraFinishedList.as_view(), name='list-finished'),
    path('create/', ObraCreate.as_view(), name='create'),
    path('update/<int:pk>/', ObraUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ObraDelete.as_view(), name='delete'),
    path('report/<int:pk>/', ReporteObra.as_view(), name='report'),
    path('finish/<int:pk>/', ObraFinish.as_view(), name='finish'),
]

obra/models.py
from django.db import models

from contratista.models import Contratista
from tipo_obra.models import Tipo_obra
from parametrizacion_multa.models import Parametrizacion
from .managers import WorkManager

class Obra(models.Model):
    tipo_obra = [
        ("Contrucción", "Construcción"),
        ("Remodelación", "Remodelación"),
        ("Reconstruccíon", "Reconstrucción"),
        ("Edificación", "Edificación")

    ]

    nombre= models.CharField(
        max_length=60, 
        unique=True,
        help_text="Ingresar solo letras")

    direccion = models.CharField(
        max_length=30,
        help_text="Ingresar una dirección valida")

    
     
    valor = models.IntegerField(
        help_text="Ingresar solo números")
    
    

    fecha_de_inicio = models.DateField(
        help_text="Ingresar la fecha dd MM yy")

    fecha_de_fin = models.DateField(
        help_text="Ingresar la fecha dd MM yy")

    estado = models.BooleanField(
        "Activo", 
        default=True)

    multa = models.IntegerField(default=0, blank=True, null=True)

    contratista = models.ForeignKey(
        Contratista, 
        on_delete=models.CASCADE,
        help_text="Ingrese nombre del contratista encargado")

    tipo_obra = models.CharField(
        max_length = 30,
        choices = tipo_obra
    )    

    parametrizacion_multa = models.ForeignKey(
         Parametrizacion,
         on_delete=models.CASCADE,
         help_text="Multa"
    )

    estados = WorkManager()

    def valor_multa(self, multa):
        if multa > 0:
            self.multa = multa
            self.save(update_fields=['multa'])   

    def mostrar_estado(self):
        if self.estado:
            mostrar_estado = "Activo"
        else:
            mostrar_estado = "Inactivo"
        
        return mostrar_estado
    
    def finalizar(self):
        if self.estado:
            self.estado = False
            self.save(update_fields=['estado'])

    def valor_multa(self, multa):
        if multa > 0:
            self.multa = multa
            self.save(update_fields=['multa'])

    def __str__(self):
        cadena = "{0}, {1}"
        return cadena.format(
            self.nombre, 
            self.direccion)

obra/forms.py
import re
from django.forms import ModelForm, HiddenInput

from .models import Obra

class ObraForm(ModelForm):
    
    class Meta:
        model = Obra
        fields = '__all__'  

        widgets = {'estado':HiddenInput()}

    def __init__(self, *args, **kwargs):
        super(ObraForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            attrs = {'class': 'form-control', 'placeholder': visible.label}
            

            visible.field.widget.attrs.update(attrs)

            if self.errors.get(visible.name, None):
                visible.field.widget.attrs.update({'class': 'form-control is-invalid'})

class ObraFinishForm(ModelForm):
    class Meta:
        model = Obra
        fields = ('estado',)

obra/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Obra
from .forms import ObraForm, ObraFinishForm
from .utils import calcular_multa

class ObraList (LoginRequiredMixin, ListView):
    model = Obra
    template_name = "obra/index.html"
    queryset = Obra.estados.valids()

class ObraExpiredList(LoginRequiredMixin, ListView):
    model = Obra
    template_name = "obra/index.html"
    queryset = Obra.estados.expireds()

    def get_queryset(self):
        queryset = super(ObraExpiredList, self).get_queryset()

        for query in queryset:
        
            multa = calcular_multa(query)
            query.valor_multa(multa)

        return queryset

class ObraFinishedList(LoginRequiredMixin, ListView):
    model = Obra
    template_name = "obra/index.html"
    queryset = Obra.estados.finisheds()

class ObraCreate(LoginRequiredMixin, CreateView):
    model = Obra
    form_class = ObraForm
    success_url = reverse_lazy('obra:list')
    template_name = 'obra/create.html'

class ObraUpdate(LoginRequiredMixin, UpdateView):
    model = Obra
    form_class = ObraForm
    success_url = reverse_lazy('obra:list')
    template_name = 'obra/update.html'

class ObraDelete(LoginRequiredMixin, DeleteView):
    model = Obra
    success_url = reverse_lazy('obra:list')
    template_name = 'obra/delete.html' 

class ObraFinish(LoginRequiredMixin, UpdateView):
    model = Obra
    form_class = ObraFinishForm
    success_url = reverse_lazy('obra:list-finished')
    template_name = 'obras/update.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.finalizar()
        form = self.get_form()
        return self.form_valid(form)


    

templates/obra/create.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <h3 class="text-center">Agregar obra <a href="{% url 'obra:list' %}">lista</a></h3>
    <form action="{% url 'obra:create' %}" method="POST">
    </br> </br> 
    </br> </br>    
        {% csrf_token %}
        {% for field in form.visible_fields %}
        {% endfor %}
        <div class="form-row">
            
            <div class="form-group col-md-6">
                <label for="textFirstName">Nombre </label>
                {{ form.nombre}}

            </div>

            <div class="form-group col-md-6">
                    <label for="textFirstName">Dirección </label>
                    {{ form.direccion}}
        
            </div>

            <div class="form-group col-md-6">
                    <label for="textFirstName">Tipo de obra</label>
                    {{ form.tipo_obra}}
        
            </div>

            <div class="form-group col-md-6">
                    <label for="textFirstName">Valor de la obra </label>
                    {{ form.valor}}
        
            </div>

            <div class="form-group col-md-6">
                    <label for="textFirstName">Fecha de Inicio </label>
                    {{ form.fecha_de_inicio}}
        
            </div>

            <div class="form-group col-md-6">
                    <label for="textFirstName">Fecha de finalización </label>
                    {{ form.fecha_de_fin}}
        
            </div>

            <div class="form-group col-xs-8 col-md-6">
                    <label for="textId">Contratista</label>
                    {{ form.contratista }}
            </div>

            <div class="form-group col-xs-8 col-md-6">
                    <label for="textId">parametrizacion</label>
                    {{ form.parametrizacion_multa }}
            </div>

            <div class="form-group col-xs-8 col-md-6">
                {{ form.estado}}
        </div>

        </br></br>
        <div class="col-xs-6 col-md-12">
            <div class="trans text-center">
            <button class="btn btn-info btn-responsive btninter" id="IdAgregar" class="btn btn-info" type="submit">Agregar</button>
            
            <button class="btn btn-danger btn-responsive btninter right" href="{% url 'obra:list' %}" id="IdCancelar" class="btn btn-danger" type="submit">Cancelar</button>

            </div>
        </div> 
    </form>
</div>
{% endblock content %}

templates/obra/delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="container">
<form action=" {% url 'obra:delete' object.id %}" method="POST">
</br>
<div class="trans text-center">
    <h3 class="text-center?">¿Desea eliminar la obra?</h3>
</div>    
</br>
<div class="col-xs-6 col-md-12">
        <div class="trans text-center">
{% csrf_token %}
{{object.nombre }}
    </div>
</div>

</br>
</br>

<div class="col-xs-6 col-md-12">
    <div class="trans text-center">
        <div class="container"></div>
        <button id="IdAgregar" class="btn btn-info btn-responsive btninter" type="submit">Eliminar</button>
        <a href="{% url 'obra:list' %}" id="IdAgregar" class="btn btn-danger btn-responsive btninter">Cancelar</a>

            

        </div>
    </div>
</div>

</form>
</div>
{% endblock content %}

templates/obra/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <div id="accordion" class="accordion central_container_accordion ">
        <div class="text-center">
            {% url 'obra:list-exprired' as url_obra %}
            {% if url_obra == request.path %}
            <h1 style="text-align: center">Contratos con multa </h1><br><br>
            {% endif %}

            {% url 'obra:list' as url_obra %}
            {% if url_obra == request.path %}
            </br></br>
            <h1 style="text-align: center">Contratos al día<a class="fas fa-fw fa-plus-circle" href="{% url 'obra:create' %}"></a></h1>
                        
            {% endif %}<br><br>

            {% url 'obra:list-finished' as url_obra %}
            {% if url_obra == request.path %}
            <h1>Contratos finalizados</a></h1><br><br>
            {% endif %}<br><br>
        </div>
        {% for obra in object_list %}
        <div class="card">
            <div class="card-header" id="heading-{{ obra.id }}">
                <h5 class="mb-0" data-toggle="collapse" data-target="#collapse-{{ obra.id }}" aria-expanded="true"
                    aria-controls="collapse-{{ obra.id }}">
                    {{ obra.nombre}}
                </h5>
            </div>

            <div id="collapse-{{ obra.id }}" class="collapse {% if forloop.first %}show{% endif %}"
                aria-labelledby="heading-{{ obra.id }}" data-parent="#accordion">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Obra: {{ obra.nombre}}</li>
                    <li class="list-group-item">Dirección: {{ obra.direccion }}</li>
                    <li class="list-group-item">Tipo obra: {{ obra.tipo_obra }}</li>
                    <li class="list-group-item">Valor: {{ obra.valor }}</li>
                    <li class="list-group-item">Tipo multa: {{ obra.parametrizacion_multa }}</li>
                    <li class="list-group-item">Valor multa: {{ obra.multa }}</li>
                    <li class="list-group-item">Fecha de inicio: {{ obra.fecha_de_inicio }}</li>
                    <li class="list-group-item">Fecha de finalización: {{ obra.fecha_de_fin }}</li>
                    <li class="list-group-item">Estado: {{ obra.mostrar_estado }}</li>
                    <li class="list-group-item">Contratista: {{ obra.contratista }}</li>
                </ul>
                <div class="text-center">
                    {% if request.user.is_staff %}
                    <div class="card-body">

                        {% url 'obra:list-finished' as url_obra %}
                        {% if not url_obra == request.path %}
                        <a href="#FinalizarModal-{{ obra.id }}" class="btn btn-success" data-toggle="modal">
                            Finalizar
                        </a>
                        <a href="{% url 'obra:update' obra.id %}" class="btn btn-info">Modificar</a>
                        {% endif %}
                        <a href="{% url 'obra:report' obra.id %}" class="btn btn-warning">Informe</a>

                        {% url 'obra:list' as url_obra %}
                        {% if url_obra == request.path %}
                        <a href="{% url 'obra:delete' obra.id %}" class="btn btn-danger">Eliminar</a>
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="modal fade" id="FinalizarModal-{{ obra.id }}" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Finalizar el contrato: {{ obra.nombre }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Nombre de la obra: {{ obra.nombre }}</li>
                            <li class="list-group-item">Dirección: {{ obra.direccion }}</li>
                            <li class="list-group-item">Tipo de obra: {{ obra.tipo_obra }}</li>
                            <li class="list-group-item">Valor: {{ obra.valor }}</li>
                            {% if obra.total_multa %}
                            <li class="list-group-item">Multa: {{ obra.total_multa }}</li>
                            {% endif %}
                            <li class="list-group-item">Fecha de inicio: {{ obra.fecha_de_inicio }}</li>
                            <li class="list-group-item">Fecha de fin: {{ obra.fecha_de_fin }}</li>
                            <li class="list-group-item">Estado: {{ obra.mostrar_estado }}</li>
                            <li class="list-group-item">Contratista: {{ obra.contratista }}</li>
                            <li class="list-group-item">parametrizacion: {{ obra.parametrizacion_multa }}</li>

                        </ul>
                    </div>
                    <div class="modal-footer">
                        <form action="{% url 'obra:finish' obra.id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="estado" value="false">
                            <button type="submit" class="btn btn-primary">Aceptar</button>
                        </form>

                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>

            
        </div>
        {% empty %}

        {% endfor %}
    </div>
    
</div>

{% endblock content %}

templates/obra/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <form action=" {% url 'obra:update' object.id %}" method="POST">        </br> </br> 
        <h3 class="text-center">Actualizar información</h3>
        


{% csrf_token %}
{% for field in form.visible_fields %}
{{ field.label_tag }}
{{ field }}
{% endfor %}
</br></br>
<div class="col-xs-6 col-md-12">
        <div class="trans text-center">
            <button class="btn btn-info btn-responsive btninter" id="IdAgregar" class="btn btn-info" type="submit">Guardar</button>
        
        <a class="btn btn-danger btn-responsive btninter right" href="{% url 'obra:list' %}" id="IdCancelar" class="btn btn-danger"
            type="submit">Cancelar</a>
        </div>
    </div> 

</form>
</div>
{% endblock content %}