contratista/urls.py
from django.urls import path
from .views import  ContratistaList, ContratistaCreate, ContratistaUpdate, ContratistaDelete 

app_name = 'contratista'

urlpatterns = [
    path('list/', ContratistaList.as_view(), name='list'),
    path('create/', ContratistaCreate.as_view(), name='create'),
    path('update/<int:pk>/', ContratistaUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ContratistaDelete.as_view(), name='delete')

    
]

gomp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('obra/', include('obra.urls', namespace='obra')),
    path('contratista/', include('contratista.urls', namespace='contratista')),
    path('parametrizacion_multa/', include('parametrizacion_multa.urls', namespace='parametrizacion')),
     path('usuario/', include('usuario.urls', namespace='usuario')),
]

contratista/models.py
from django.db import models

from django.db import models

class Contratista(models.Model):
    primer_nombre = models.CharField(
        max_length=15,
        help_text="Ingresar solo letras")


    segundo_nombre = models.CharField(
        max_length=15, blank=True,
        null=True,
        help_text="Ingresar solo letras")


    primer_apellido = models.CharField(
        max_length=15,
        help_text="Ingresar solo letras")


    segundo_apellido = models.CharField(
        max_length=15, blank=True,
        null=True,
        help_text="Ingresar solo letras")


    documento_identidad = models.IntegerField(
        unique=True,
        help_text="Ingresar solo números")


    direccion = models.CharField(
        max_length=35)


    telefono = models.IntegerField(
        help_text="Ingresar solo números")


    def nombre_completo(self):
        if self.segundo_nombre:
            nombre = "{0} {1} {2} {3}".format(
                self.primer_apellido,
                self.segundo_apellido,
                self.primer_nombre,
                self.segundo_nombre)
        else:
            nombre = "{0} {1} {2}".format(
                self.primer_apellido,
                self.segundo_apellido,
                self.primer_nombre)

        return nombre


    def __str__(self):
        return self.nombre_completo()

contratista/forms.py
import re
from django.forms import ModelForm

from .models import Contratista

class ContratistaForm(ModelForm):
    
    class Meta:
        model = Contratista
        fields = '__all__'  

    def __init__(self, *args, **kwargs):
        super(ContratistaForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            attrs = {'class': 'form-control', 'placeholder': visible.label}
            

            visible.field.widget.attrs.update(attrs)

            if self.errors.get(visible.name, None):
                visible.field.widget.attrs.update({'class': 'form-control is-invalid'})

contratista/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Contratista
from .forms import ContratistaForm

class ContratistaList (LoginRequiredMixin, ListView):
    model = Contratista
    template_name = "contratista/index.html"

class ContratistaCreate(LoginRequiredMixin, CreateView):
    model = Contratista
    form_class = ContratistaForm
    success_url = reverse_lazy('contratista:create')
    template_name = 'contratista/create.html'

class ContratistaUpdate(LoginRequiredMixin, UpdateView):
    model = Contratista
    form_class = ContratistaForm
    success_url = reverse_lazy('contratista:list')
    template_name = 'contratista/update.html'

class ContratistaDelete(LoginRequiredMixin, DeleteView):
    model = Contratista
    success_url = reverse_lazy('contratista:list')
    template_name = 'contratista/delete.html'

templates/contratista/create.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
   
    

    <form action="{% url 'contratista:create' %}" method="POST">
        <h3 class="text-center">Agregar contratista <a href="{% url 'contratista:list' %}">lista</a></h3>
</br> </br> 
    </br> </br>    
        {% csrf_token %}
        {% for field in form.visible_fields %}
        {% endfor %}
        <div class="form-row">
            
            <div class="form-group col-md-6">
                <label for="textFirstName">Primer Nombre </label>
                {{ form.primer_nombre}}

            </div>

            <div class="form-group col-md-6">
                    <label for="textFirstName">Segundo Nombre </label>
                    {{ form.segundo_nombre}}
        
            </div>

            <div class="form-group col-md-6">
                <label for="textFirstName">Primer Apellido</label>
                {{ form.primer_apellido}}
    
        </div>

        <div class="form-group col-md-6">
                <label for="textFirstName">Segundo Apellido </label>
                {{ form.segundo_apellido}}
    
        </div>

        <div class="form-group col-md-6">
                <label for="textFirstName">Identificación </label>
                {{ form.documento_identidad}}
    
        </div>

        <div class="form-group col-md-6">
                <label for="textFirstName">Dirección</label>
                {{ form.direccion}}

        </div>

            

        <div class="form-group col-md-6">
                <label for="textFirstName">Teléfono </label>
                {{ form.telefono}}

        </div>

        

        </br></br>
        <div class="col-xs-6 col-md-12">
            <div class="trans text-center">
                <button class="btn btn-info btn-responsive btninter" id="IdAgregar"  type="submit">Agregar</button>
                
                <a class="btn btn-danger" href="{% url 'contratista:list' %}" id="IdCancelar">Cancelar</a>
            
            </div>
        </div> 
    </form>
</div>
{% endblock content %}

templates/contratista/delete.html
ss{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="container">
<form action=" {% url 'contratista:delete' object.id %}" method="POST">
</br>
<div class="trans text-center">
    <h3 class="text-center?">¿Desea eliminar el contratista?</h3>
</div>
</br>
<div class="col-xs-6 col-md-12">
        <div class="trans text-center">
{% csrf_token %}
{{object.nombre_completo}}
    </div>
</div>

</br>
</br>

<div class="col-xs-6 col-md-12">
    <div class="trans text-center">
        <div class="container"></div>

            <button id="IdAgregar" class="btn btn-info btn-responsive btninter" type="submit">Eliminar</button>
            <a href="{% url 'contratista:list' %}" id="IdAgregar" class="btn btn-danger btn-responsive btninter">Cancelar</a>

        </div>
    </div>
</div>

</form>
</div>
{% endblock content %}

templates/contratista/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <h1 style="text-align: center">Contratistas <a class="fas fa-user-plus" href="{% url 'contratista:create' %}"></a>
    </h1><br><br>
    <div id="accordion" class="accordion central_container_accordion">
        {% for contratista in object_list %}
        <div class="card">
            <div class="card-header" id="heading-{{ contratista.id }}">
                <h5 class="mb-0" data-toggle="collapse" data-target="#collapse-{{ contratista.id }}"
                    aria-expanded="true" aria-controls="collapse-{{ contratista.id }}">
                    {{ contratista.nombre_completo }}
                </h5>
            </div>

            <div id="collapse-{{ contratista.id }}" class="collapse {% if forloop.first %}show{% endif %}"
                aria-labelledby="heading-{{ contratista.id }}" data-parent="#accordion">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Contratista: {{ contratista.nombre_completo }}</li>
                    <li class="list-group-item">Documento: {{ contratista.documento_identidad }}</li>
                    <li class="list-group-item">Dirección: {{ contratista.direccion }}</li>
                    <li class="list-group-item">Teléfono: {{ contratista.telefono }}</li>
                </ul>
                <div class="text-center">
                    {% if request.user.is_staff %}<div class="card-body">
                        <a href="{% url 'contratista:update' contratista.id %}" class="btn btn-info">Modificar</a>
                        <a href="{% url 'contratista:delete' contratista.id %}" class="btn btn-danger">Eliminar</a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        {% empty %}

        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/contratista/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
<form action=" {% url 'contratista:update' object.id %}" method="POST">
    </br> </br> 
    <h3 class="text-center">Actualizar información</h3>
{% csrf_token %}
{% for field in form.visible_fields %}
{{ field.label_tag }}
{{ field }}
{% endfor %}
</br></br>
<div class="col-xs-6 col-md-12">
        <div class="trans text-center">
        <button class="btn btn-info btn-responsive btninter" id="IdAgregar" class="btn btn-info" type="submit">Agregar</button>
        
        <button class="btn btn-danger btn-responsive btninter right" href="{% url 'contratista:list' %}" id="IdCancelar" class="btn btn-danger"
            type="submit">Cancelar</button>

        </div>
    </div> 

</form>
</div>
{% endblock content %}