gomp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('obra/', include('obra.urls', namespace='obra')),
    path('contratista/', include('contratista.urls', namespace='contratista')),
    path('parametrizacion_multa/', include('parametrizacion_multa.urls', namespace='parametrizacion')),
     path('usuario/', include('usuario.urls', namespace='usuario')),
]

obra/urls.py
from django.urls import path
from .views import  ObraList, ObraCreate, ObraExpiredList, ObraUpdate, ObraDelete, ObraFinish, ObraFinishedList
from .reportes.obras import ReporteObra

app_name = 'obra'

urlpatterns = [
    path('list/', ObraList.as_view(), name='list'),
    path('expired/', ObraExpiredList.as_view(), name='list-exprired'),
    path('finished/', ObraFinishedList.as_view(), name='list-finished'),
    path('create/', ObraCreate.as_view(), name='create'),
    path('update/<int:pk>/', ObraUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ObraDelete.as_view(), name='delete'),
    path('report/<int:pk>/', ReporteObra.as_view(), name='report'),
    path('finish/<int:pk>/', ObraFinish.as_view(), name='finish'),
]

parametrizacion_multa/urls.py
from django.urls import path
from .views import ParametrizacionList, ParametrizacionCreate, ParametrizacionDelete, ParametrizacionUpdate
app_name = 'parametrizacion_multa'

urlpatterns = [
    path('list/',ParametrizacionList.as_view(), name='list'),
    path('create/',ParametrizacionCreate.as_view(), name='create'),
    path('update/<int:pk>/', ParametrizacionUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ParametrizacionDelete.as_view(), name='delete'),

]

usuario/urls.py
from django.urls import path
from .views import UsuarioCreate, LoginView, UsuarioList, UsuarioDelete, UsuarioUpdate, LogoutView

app_name = "usuario"

urlpatterns = [
    path('list/', UsuarioList.as_view(), name='list'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/',UsuarioCreate.as_view(), name='create'),
    path('update/<int:pk>/', UsuarioUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', UsuarioDelete.as_view(), name='delete')
]

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">GOMP</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'contratista:list' %}">Contratista</a>
            <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Obras
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'obra:list' %}">Activas</a>
                      <a class="dropdown-item" href="{% url 'obra:list-exprired' %}">Expiradas</a>
                      <a class="dropdown-item" href="{% url 'obra:list-finished' %}">Finalizadas</a>
                    </div>
                  </li>
            {% if request.user.is_staff %}
            <a class="nav-item nav-link" href="{% url 'parametrizacion_multa:list' %}">Parametrización Multa</a>
            <a class="nav-item nav-link" href="{% url 'usuario:list' %}">Operario</a>
            {% endif %}
        </div>
    </div>

    {% if request.user.is_staff %}
    <p class="text-light">Administrador: {{ request.user.first_name }} {{ request.user.last_name }}</p>
    {% endif %}

    {% if not request.user.is_staff %}
    <p class="text-light">Operario:  {{ request.user.first_name }} {{ request.user.last_name }} </p>
    {% endif %}

    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-circle fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Cerrar sesión</a>
            </div>
        </li>
    </ul>
</nav>

<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cerrar Sesión</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">¿Está seguro de cerrar sesión?, para confirmar presione el botón Salir.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a class="btn btn-primary" href="{% url 'usuario:logout' %}">Salir</a>
            </div>
        </div>
    </div>
</div>